### ISSUE TITLE
依赖下载错误

### ISSUE THREAD

**Issue by inverai** [YaoZeyuan/zhihuhelp_with_node#1]
执行 下载依赖的时候出现的错误，
![image](https://user-images.githubusercontent.com/17284308/52861194-aff7ea80-316c-11e9-9bbd-6dee62a3989c.png)

![image](https://user-images.githubusercontent.com/17284308/52861154-8f2f9500-316c-11e9-8be3-fccb286d55ec.png)

**Comment by YaoZeyuan** [comment]
嗯, 试一下新版吧, 这里应该是`electron-builder install-app-deps`
