### ISSUE TITLE
希望您能换一个云盘来分享文件

### ISSUE THREAD

**Issue by beibaodong** [YaoZeyuan/zhihuhelp_with_node#10]
百度网盘的下载速度实在是太慢，而且还要调用客户端。
建议使用腾讯微云或者蓝奏云。

**Comment by sunboy166** [comment]
要求太多了。。。

**Comment by mldxtj** [comment]
同意楼上

**Comment by ykla** [comment]
直接通过github 发布即可

**Comment by YaoZeyuan** [comment]
> 直接通过github 发布即可

done => https://github.com/YaoZeyuan/zhihuhelp_with_node/releases/tag/2.3.0

& 坦诚说, 目前还是百度云比较稳. 我都没有微云账户🤣
