### ISSUE TITLE
安装后提示 Java 运行错误

### ISSUE THREAD

**Issue by ykla** [YaoZeyuan/zhihuhelp_with_node#13]
![3BT`YYE}A7 9@WC5 ~NKNG](https://user-images.githubusercontent.com/10327999/54330002-0adb0f80-464f-11e9-9b94-afda9e587350.png)

**Comment by ykla** [comment]
权限问题，需要管理员权限，请修复该bug

**Comment by YaoZeyuan** [comment]
用管理员账户跑吧, 或者升级下系统. Win10上没有这个问题

其实我觉得你肯定是哪一步搞错了, 是不是选择安装用户的时候选的是: 给所有用户安装?

改成"只为当前用户安装"就好了
