### ISSUE TITLE
图片是被知乎压缩过的

### ISSUE THREAD

**Issue by Sherry720** [YaoZeyuan/zhihuhelp_with_node#15]
借用知乎评论区：
知乎会压缩图片，下载的图片地址是xxxxxx_b.jpg 或者xxxxxx_hd.jpg，但实际上原图是xxxxxx.jpg

**Comment by YaoZeyuan** [comment]
2.3.0中添加了原图选项, 试下呗

**Comment by Sherry720** [comment]
好的，谢谢告知
