### ISSUE TITLE
输出错误

### ISSUE THREAD

**Issue by inverai** [YaoZeyuan/zhihuhelp_with_node#3]
很怀疑你是否通过了你列出的测试用例，  专栏输出的电子书是空， 话题则是空文件夹，，

![image](https://user-images.githubusercontent.com/17284308/52908561-4c2c0980-32b3-11e9-9233-e362a483365c.png)
![image](https://user-images.githubusercontent.com/17284308/52908564-5817cb80-32b3-11e9-8f0b-d0de316f1af6.png)

**Comment by YaoZeyuan** [comment]
![image](https://user-images.githubusercontent.com/7150325/52916500-34886b80-331b-11e9-98d1-f355cdc69f8e.png)

感谢反馈, 专题信息获取 & 话题电子书渲染出问题了, 我改一下

**Comment by YaoZeyuan** [comment]
知乎这个浓眉大眼的把专栏接口换了...已修复

**Comment by YaoZeyuan** [comment]
问题已修复
