### ISSUE TITLE
多平台支持

### ISSUE THREAD

**Issue by xplorld** [YaoZeyuan/zhihuhelp_with_node#5]
希望有 macOS 和 Linux 的系统支持。既然是 node 的工程应该可以实现。

**Comment by ykla** [comment]
这样再加下 FreeBSD

**Comment by liguobao** [comment]
现在能直接在Mac上运行源码吗?

**Comment by YaoZeyuan** [comment]
说来惭愧...我没有Mac🤣

**Comment by YaoZeyuan** [comment]
> 现在能直接在Mac上运行源码吗?

可以的.  你按readme里搭建好开发环境就能跑起来

**Comment by YaoZeyuan** [comment]
搞定, mac版下载地址 => https://pan.baidu.com/s/1CaTrUGAcBjEbsMN39-4iaw
