### ISSUE TITLE
程序运行错误

### ISSUE THREAD

**Issue by sunboy166** [YaoZeyuan/zhihuhelp_with_node#6]
我登录了自己的账号，然后试了 爬取收藏夹，关注的人的回答，点赞等等。。都会报同一个错误。。麻烦您看一下。
![image](https://user-images.githubusercontent.com/19704226/53019365-85b96c00-348f-11e9-9771-9ffb2b06192b.png)

**Comment by sunboy166** [comment]
都会 提示 typeError:cannot read property 'question' of undefined

**Comment by YaoZeyuan** [comment]
首次登陆时没能载入cookie, 关掉重开一次
