### ISSUE TITLE
无法生成epub和html文件

### ISSUE THREAD

**Issue by zxhycxq** [YaoZeyuan/zhihuhelp_with_node#8]
百度云 2019-02-16 22:41 版本好为1.0.0 的。
生成的epub和html文件夹下面都是空的
以 https://www.zhihu.com/people/cheng-shi-xi-ren-6/answers 为例

**Comment by zxhycxq** [comment]
以 https://www.zhihu.com/people/cheng-shi-xi-ren-6/answers  为例

**Comment by YaoZeyuan** [comment]
这是1.0.0版的bug, 更新到2.1.0版本即可

**Comment by zxhycxq** [comment]
没有找到升级的地方，点击GitHub上面的链接，看着也是1.0.0版本的
